// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/repository/address_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/delivery/repository/address_repository.go -destination=./shared/mock/repository/address_repository_mock.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	presenter "github.com/Temisaputra/warOnk/internal/delivery/presenter"
	request "github.com/Temisaputra/warOnk/internal/delivery/presenter/request"
	response "github.com/Temisaputra/warOnk/internal/delivery/presenter/response"
	entity "github.com/Temisaputra/warOnk/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAddressRepository is a mock of AddressRepository interface.
type MockAddressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAddressRepositoryMockRecorder
	isgomock struct{}
}

// MockAddressRepositoryMockRecorder is the mock recorder for MockAddressRepository.
type MockAddressRepositoryMockRecorder struct {
	mock *MockAddressRepository
}

// NewMockAddressRepository creates a new mock instance.
func NewMockAddressRepository(ctrl *gomock.Controller) *MockAddressRepository {
	mock := &MockAddressRepository{ctrl: ctrl}
	mock.recorder = &MockAddressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressRepository) EXPECT() *MockAddressRepositoryMockRecorder {
	return m.recorder
}

// CreateAddress mocks base method.
func (m *MockAddressRepository) CreateAddress(ctx context.Context, address *entity.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddress", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddress indicates an expected call of CreateAddress.
func (mr *MockAddressRepositoryMockRecorder) CreateAddress(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddress", reflect.TypeOf((*MockAddressRepository)(nil).CreateAddress), ctx, address)
}

// DeleteAddress mocks base method.
func (m *MockAddressRepository) DeleteAddress(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockAddressRepositoryMockRecorder) DeleteAddress(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockAddressRepository)(nil).DeleteAddress), ctx, id)
}

// DeleteAddressByIdSupplier mocks base method.
func (m *MockAddressRepository) DeleteAddressByIdSupplier(ctx context.Context, supplierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddressByIdSupplier", ctx, supplierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddressByIdSupplier indicates an expected call of DeleteAddressByIdSupplier.
func (mr *MockAddressRepositoryMockRecorder) DeleteAddressByIdSupplier(ctx, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddressByIdSupplier", reflect.TypeOf((*MockAddressRepository)(nil).DeleteAddressByIdSupplier), ctx, supplierID)
}

// GetAddressByID mocks base method.
func (m *MockAddressRepository) GetAddressByID(ctx context.Context, id int) (*presenter.AddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressByID", ctx, id)
	ret0, _ := ret[0].(*presenter.AddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressByID indicates an expected call of GetAddressByID.
func (mr *MockAddressRepositoryMockRecorder) GetAddressByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressByID", reflect.TypeOf((*MockAddressRepository)(nil).GetAddressByID), ctx, id)
}

// GetAddressByIdSupplier mocks base method.
func (m *MockAddressRepository) GetAddressByIdSupplier(ctx context.Context, supplierID int) (*entity.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressByIdSupplier", ctx, supplierID)
	ret0, _ := ret[0].(*entity.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressByIdSupplier indicates an expected call of GetAddressByIdSupplier.
func (mr *MockAddressRepositoryMockRecorder) GetAddressByIdSupplier(ctx, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressByIdSupplier", reflect.TypeOf((*MockAddressRepository)(nil).GetAddressByIdSupplier), ctx, supplierID)
}

// GetAllAddress mocks base method.
func (m *MockAddressRepository) GetAllAddress(ctx context.Context, pagination *request.Pagination, params *presenter.AddressRequest) ([]*presenter.AddressResponse, response.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAddress", ctx, pagination, params)
	ret0, _ := ret[0].([]*presenter.AddressResponse)
	ret1, _ := ret[1].(response.Meta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllAddress indicates an expected call of GetAllAddress.
func (mr *MockAddressRepositoryMockRecorder) GetAllAddress(ctx, pagination, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAddress", reflect.TypeOf((*MockAddressRepository)(nil).GetAllAddress), ctx, pagination, params)
}

// UpdateAddress mocks base method.
func (m *MockAddressRepository) UpdateAddress(ctx context.Context, address *entity.Address, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, address, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockAddressRepositoryMockRecorder) UpdateAddress(ctx, address, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockAddressRepository)(nil).UpdateAddress), ctx, address, id)
}
