// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/repository/contact_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/delivery/repository/contact_repository.go -destination=./shared/mock/repository/contact_repository_mock.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	presenter "github.com/Temisaputra/warOnk/internal/delivery/presenter"
	request "github.com/Temisaputra/warOnk/internal/delivery/presenter/request"
	response "github.com/Temisaputra/warOnk/internal/delivery/presenter/response"
	entity "github.com/Temisaputra/warOnk/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockContactRepository is a mock of ContactRepository interface.
type MockContactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContactRepositoryMockRecorder
	isgomock struct{}
}

// MockContactRepositoryMockRecorder is the mock recorder for MockContactRepository.
type MockContactRepositoryMockRecorder struct {
	mock *MockContactRepository
}

// NewMockContactRepository creates a new mock instance.
func NewMockContactRepository(ctrl *gomock.Controller) *MockContactRepository {
	mock := &MockContactRepository{ctrl: ctrl}
	mock.recorder = &MockContactRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactRepository) EXPECT() *MockContactRepositoryMockRecorder {
	return m.recorder
}

// CreateContact mocks base method.
func (m *MockContactRepository) CreateContact(ctx context.Context, contact *entity.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockContactRepositoryMockRecorder) CreateContact(ctx, contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockContactRepository)(nil).CreateContact), ctx, contact)
}

// DeleteContact mocks base method.
func (m *MockContactRepository) DeleteContact(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContact", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContact indicates an expected call of DeleteContact.
func (mr *MockContactRepositoryMockRecorder) DeleteContact(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContact", reflect.TypeOf((*MockContactRepository)(nil).DeleteContact), ctx, id)
}

// DeleteContactByIdSupplier mocks base method.
func (m *MockContactRepository) DeleteContactByIdSupplier(ctx context.Context, supplierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContactByIdSupplier", ctx, supplierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContactByIdSupplier indicates an expected call of DeleteContactByIdSupplier.
func (mr *MockContactRepositoryMockRecorder) DeleteContactByIdSupplier(ctx, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContactByIdSupplier", reflect.TypeOf((*MockContactRepository)(nil).DeleteContactByIdSupplier), ctx, supplierID)
}

// GetAllContact mocks base method.
func (m *MockContactRepository) GetAllContact(ctx context.Context, pagination *request.Pagination, params *presenter.ContactRequest) ([]*presenter.ContactResponse, response.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllContact", ctx, pagination, params)
	ret0, _ := ret[0].([]*presenter.ContactResponse)
	ret1, _ := ret[1].(response.Meta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllContact indicates an expected call of GetAllContact.
func (mr *MockContactRepositoryMockRecorder) GetAllContact(ctx, pagination, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllContact", reflect.TypeOf((*MockContactRepository)(nil).GetAllContact), ctx, pagination, params)
}

// GetContactByID mocks base method.
func (m *MockContactRepository) GetContactByID(ctx context.Context, id int) (*presenter.ContactResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByID", ctx, id)
	ret0, _ := ret[0].(*presenter.ContactResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByID indicates an expected call of GetContactByID.
func (mr *MockContactRepositoryMockRecorder) GetContactByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByID", reflect.TypeOf((*MockContactRepository)(nil).GetContactByID), ctx, id)
}

// GetContactByIdSupplier mocks base method.
func (m *MockContactRepository) GetContactByIdSupplier(ctx context.Context, supplierID int) (*entity.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByIdSupplier", ctx, supplierID)
	ret0, _ := ret[0].(*entity.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByIdSupplier indicates an expected call of GetContactByIdSupplier.
func (mr *MockContactRepositoryMockRecorder) GetContactByIdSupplier(ctx, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByIdSupplier", reflect.TypeOf((*MockContactRepository)(nil).GetContactByIdSupplier), ctx, supplierID)
}

// UpdateContact mocks base method.
func (m *MockContactRepository) UpdateContact(ctx context.Context, contact *entity.Contact, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContact", ctx, contact, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContact indicates an expected call of UpdateContact.
func (mr *MockContactRepositoryMockRecorder) UpdateContact(ctx, contact, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContact", reflect.TypeOf((*MockContactRepository)(nil).UpdateContact), ctx, contact, id)
}
