// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/repository/group_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/delivery/repository/group_repository.go -destination=./shared/mock/repository/group_repository_mock.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	presenter "github.com/Temisaputra/warOnk/internal/delivery/presenter"
	request "github.com/Temisaputra/warOnk/internal/delivery/presenter/request"
	response "github.com/Temisaputra/warOnk/internal/delivery/presenter/response"
	entity "github.com/Temisaputra/warOnk/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupRepository is a mock of GroupRepository interface.
type MockGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockGroupRepositoryMockRecorder is the mock recorder for MockGroupRepository.
type MockGroupRepositoryMockRecorder struct {
	mock *MockGroupRepository
}

// NewMockGroupRepository creates a new mock instance.
func NewMockGroupRepository(ctrl *gomock.Controller) *MockGroupRepository {
	mock := &MockGroupRepository{ctrl: ctrl}
	mock.recorder = &MockGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepository) EXPECT() *MockGroupRepositoryMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockGroupRepository) CreateGroup(ctx context.Context, group *[]entity.SupplierGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupRepositoryMockRecorder) CreateGroup(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupRepository)(nil).CreateGroup), ctx, group)
}

// CreateGroups mocks base method.
func (m *MockGroupRepository) CreateGroups(ctx context.Context, groups presenter.GroupRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroups", ctx, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroups indicates an expected call of CreateGroups.
func (mr *MockGroupRepositoryMockRecorder) CreateGroups(ctx, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroups", reflect.TypeOf((*MockGroupRepository)(nil).CreateGroups), ctx, groups)
}

// DeleteGroup mocks base method.
func (m *MockGroupRepository) DeleteGroup(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupRepositoryMockRecorder) DeleteGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroupRepository)(nil).DeleteGroup), ctx, id)
}

// DeleteGroupByIdSupplier mocks base method.
func (m *MockGroupRepository) DeleteGroupByIdSupplier(ctx context.Context, supplierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroupByIdSupplier", ctx, supplierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroupByIdSupplier indicates an expected call of DeleteGroupByIdSupplier.
func (mr *MockGroupRepositoryMockRecorder) DeleteGroupByIdSupplier(ctx, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupByIdSupplier", reflect.TypeOf((*MockGroupRepository)(nil).DeleteGroupByIdSupplier), ctx, supplierID)
}

// GetAllGroups mocks base method.
func (m *MockGroupRepository) GetAllGroups(ctx context.Context, pagination *request.Pagination) ([]*presenter.GroupResponse, response.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGroups", ctx, pagination)
	ret0, _ := ret[0].([]*presenter.GroupResponse)
	ret1, _ := ret[1].(response.Meta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllGroups indicates an expected call of GetAllGroups.
func (mr *MockGroupRepositoryMockRecorder) GetAllGroups(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGroups", reflect.TypeOf((*MockGroupRepository)(nil).GetAllGroups), ctx, pagination)
}

// GetGroupByID mocks base method.
func (m *MockGroupRepository) GetGroupByID(ctx context.Context, id int) (*presenter.GroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, id)
	ret0, _ := ret[0].(*presenter.GroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockGroupRepositoryMockRecorder) GetGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockGroupRepository)(nil).GetGroupByID), ctx, id)
}

// GetGroupByIdSupplier mocks base method.
func (m *MockGroupRepository) GetGroupByIdSupplier(ctx context.Context, supplierID int) (*entity.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByIdSupplier", ctx, supplierID)
	ret0, _ := ret[0].(*entity.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByIdSupplier indicates an expected call of GetGroupByIdSupplier.
func (mr *MockGroupRepositoryMockRecorder) GetGroupByIdSupplier(ctx, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByIdSupplier", reflect.TypeOf((*MockGroupRepository)(nil).GetGroupByIdSupplier), ctx, supplierID)
}

// UpdateGroup mocks base method.
func (m *MockGroupRepository) UpdateGroup(ctx context.Context, group *entity.SupplierGroup, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, group, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupRepositoryMockRecorder) UpdateGroup(ctx, group, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroupRepository)(nil).UpdateGroup), ctx, group, id)
}

// UpdateGroups mocks base method.
func (m *MockGroupRepository) UpdateGroups(ctx context.Context, groups presenter.GroupRequest, groupID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroups", ctx, groups, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroups indicates an expected call of UpdateGroups.
func (mr *MockGroupRepositoryMockRecorder) UpdateGroups(ctx, groups, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroups", reflect.TypeOf((*MockGroupRepository)(nil).UpdateGroups), ctx, groups, groupID)
}
