// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/repository/material_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/delivery/repository/material_repository.go -destination=./shared/mock/repository/material_repository_mock.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	presenter "github.com/Temisaputra/warOnk/internal/delivery/presenter"
	request "github.com/Temisaputra/warOnk/internal/delivery/presenter/request"
	response "github.com/Temisaputra/warOnk/internal/delivery/presenter/response"
	entity "github.com/Temisaputra/warOnk/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMaterialRepository is a mock of MaterialRepository interface.
type MockMaterialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMaterialRepositoryMockRecorder
	isgomock struct{}
}

// MockMaterialRepositoryMockRecorder is the mock recorder for MockMaterialRepository.
type MockMaterialRepositoryMockRecorder struct {
	mock *MockMaterialRepository
}

// NewMockMaterialRepository creates a new mock instance.
func NewMockMaterialRepository(ctrl *gomock.Controller) *MockMaterialRepository {
	mock := &MockMaterialRepository{ctrl: ctrl}
	mock.recorder = &MockMaterialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaterialRepository) EXPECT() *MockMaterialRepositoryMockRecorder {
	return m.recorder
}

// CreateMaterial mocks base method.
func (m *MockMaterialRepository) CreateMaterial(ctx context.Context, material *[]entity.MaterialList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMaterial", ctx, material)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMaterial indicates an expected call of CreateMaterial.
func (mr *MockMaterialRepositoryMockRecorder) CreateMaterial(ctx, material any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMaterial", reflect.TypeOf((*MockMaterialRepository)(nil).CreateMaterial), ctx, material)
}

// DeleteMaterial mocks base method.
func (m *MockMaterialRepository) DeleteMaterial(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaterial", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMaterial indicates an expected call of DeleteMaterial.
func (mr *MockMaterialRepositoryMockRecorder) DeleteMaterial(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaterial", reflect.TypeOf((*MockMaterialRepository)(nil).DeleteMaterial), ctx, id)
}

// DeleteMaterialByIdSupplier mocks base method.
func (m *MockMaterialRepository) DeleteMaterialByIdSupplier(ctx context.Context, supplierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaterialByIdSupplier", ctx, supplierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMaterialByIdSupplier indicates an expected call of DeleteMaterialByIdSupplier.
func (mr *MockMaterialRepositoryMockRecorder) DeleteMaterialByIdSupplier(ctx, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaterialByIdSupplier", reflect.TypeOf((*MockMaterialRepository)(nil).DeleteMaterialByIdSupplier), ctx, supplierID)
}

// GetAllMaterial mocks base method.
func (m *MockMaterialRepository) GetAllMaterial(ctx context.Context, pagination *request.Pagination, params *presenter.MaterialRequest) ([]*presenter.MaterialResponse, response.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMaterial", ctx, pagination, params)
	ret0, _ := ret[0].([]*presenter.MaterialResponse)
	ret1, _ := ret[1].(response.Meta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllMaterial indicates an expected call of GetAllMaterial.
func (mr *MockMaterialRepositoryMockRecorder) GetAllMaterial(ctx, pagination, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMaterial", reflect.TypeOf((*MockMaterialRepository)(nil).GetAllMaterial), ctx, pagination, params)
}

// GetMaterialByID mocks base method.
func (m *MockMaterialRepository) GetMaterialByID(ctx context.Context, id int) (*presenter.MaterialResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialByID", ctx, id)
	ret0, _ := ret[0].(*presenter.MaterialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterialByID indicates an expected call of GetMaterialByID.
func (mr *MockMaterialRepositoryMockRecorder) GetMaterialByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialByID", reflect.TypeOf((*MockMaterialRepository)(nil).GetMaterialByID), ctx, id)
}

// GetMaterialByIdSupplier mocks base method.
func (m *MockMaterialRepository) GetMaterialByIdSupplier(ctx context.Context, supplierID int) (*[]entity.MaterialList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialByIdSupplier", ctx, supplierID)
	ret0, _ := ret[0].(*[]entity.MaterialList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterialByIdSupplier indicates an expected call of GetMaterialByIdSupplier.
func (mr *MockMaterialRepositoryMockRecorder) GetMaterialByIdSupplier(ctx, supplierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialByIdSupplier", reflect.TypeOf((*MockMaterialRepository)(nil).GetMaterialByIdSupplier), ctx, supplierID)
}

// UpdateMaterial mocks base method.
func (m *MockMaterialRepository) UpdateMaterial(ctx context.Context, material *[]entity.MaterialList, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaterial", ctx, material, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMaterial indicates an expected call of UpdateMaterial.
func (mr *MockMaterialRepositoryMockRecorder) UpdateMaterial(ctx, material, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaterial", reflect.TypeOf((*MockMaterialRepository)(nil).UpdateMaterial), ctx, material, id)
}
