// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/repository/supplier_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/delivery/repository/supplier_repository.go -destination=./shared/mock/repository/supplier_repository_mock.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	presenter "github.com/Temisaputra/warOnk/internal/delivery/presenter"
	request "github.com/Temisaputra/warOnk/internal/delivery/presenter/request"
	response "github.com/Temisaputra/warOnk/internal/delivery/presenter/response"
	entity "github.com/Temisaputra/warOnk/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSupplierRepository is a mock of SupplierRepository interface.
type MockSupplierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSupplierRepositoryMockRecorder
	isgomock struct{}
}

// MockSupplierRepositoryMockRecorder is the mock recorder for MockSupplierRepository.
type MockSupplierRepositoryMockRecorder struct {
	mock *MockSupplierRepository
}

// NewMockSupplierRepository creates a new mock instance.
func NewMockSupplierRepository(ctrl *gomock.Controller) *MockSupplierRepository {
	mock := &MockSupplierRepository{ctrl: ctrl}
	mock.recorder = &MockSupplierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupplierRepository) EXPECT() *MockSupplierRepositoryMockRecorder {
	return m.recorder
}

// BlockUnblockSupplier mocks base method.
func (m *MockSupplierRepository) BlockUnblockSupplier(ctx context.Context, id int, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUnblockSupplier", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockUnblockSupplier indicates an expected call of BlockUnblockSupplier.
func (mr *MockSupplierRepositoryMockRecorder) BlockUnblockSupplier(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUnblockSupplier", reflect.TypeOf((*MockSupplierRepository)(nil).BlockUnblockSupplier), ctx, id, status)
}

// CreateSupplier mocks base method.
func (m *MockSupplierRepository) CreateSupplier(ctx context.Context, supplier *presenter.SupplierRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupplier", ctx, supplier)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSupplier indicates an expected call of CreateSupplier.
func (mr *MockSupplierRepositoryMockRecorder) CreateSupplier(ctx, supplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupplier", reflect.TypeOf((*MockSupplierRepository)(nil).CreateSupplier), ctx, supplier)
}

// DeleteSupplier mocks base method.
func (m *MockSupplierRepository) DeleteSupplier(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplier", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSupplier indicates an expected call of DeleteSupplier.
func (mr *MockSupplierRepositoryMockRecorder) DeleteSupplier(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplier", reflect.TypeOf((*MockSupplierRepository)(nil).DeleteSupplier), ctx, id)
}

// ExportSupplier mocks base method.
func (m *MockSupplierRepository) ExportSupplier(ctx context.Context, params *presenter.SupplierRequest) ([]presenter.SupplierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportSupplier", ctx, params)
	ret0, _ := ret[0].([]presenter.SupplierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportSupplier indicates an expected call of ExportSupplier.
func (mr *MockSupplierRepositoryMockRecorder) ExportSupplier(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportSupplier", reflect.TypeOf((*MockSupplierRepository)(nil).ExportSupplier), ctx, params)
}

// GetAllSupplier mocks base method.
func (m *MockSupplierRepository) GetAllSupplier(ctx context.Context, pagination *request.Pagination, params *presenter.SupplierRequest) ([]*presenter.SupplierResponse, response.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSupplier", ctx, pagination, params)
	ret0, _ := ret[0].([]*presenter.SupplierResponse)
	ret1, _ := ret[1].(response.Meta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllSupplier indicates an expected call of GetAllSupplier.
func (mr *MockSupplierRepositoryMockRecorder) GetAllSupplier(ctx, pagination, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSupplier", reflect.TypeOf((*MockSupplierRepository)(nil).GetAllSupplier), ctx, pagination, params)
}

// GetSupplierByID mocks base method.
func (m *MockSupplierRepository) GetSupplierByID(ctx context.Context, id int) (*presenter.SupplierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplierByID", ctx, id)
	ret0, _ := ret[0].(*presenter.SupplierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplierByID indicates an expected call of GetSupplierByID.
func (mr *MockSupplierRepositoryMockRecorder) GetSupplierByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplierByID", reflect.TypeOf((*MockSupplierRepository)(nil).GetSupplierByID), ctx, id)
}

// InsertHistorySupplier mocks base method.
func (m *MockSupplierRepository) InsertHistorySupplier(ctx context.Context, history *entity.StatusHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHistorySupplier", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertHistorySupplier indicates an expected call of InsertHistorySupplier.
func (mr *MockSupplierRepositoryMockRecorder) InsertHistorySupplier(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHistorySupplier", reflect.TypeOf((*MockSupplierRepository)(nil).InsertHistorySupplier), ctx, history)
}

// UpdateSupplier mocks base method.
func (m *MockSupplierRepository) UpdateSupplier(ctx context.Context, supplier *presenter.SupplierRequest, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupplier", ctx, supplier, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSupplier indicates an expected call of UpdateSupplier.
func (mr *MockSupplierRepositoryMockRecorder) UpdateSupplier(ctx, supplier, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupplier", reflect.TypeOf((*MockSupplierRepository)(nil).UpdateSupplier), ctx, supplier, id)
}
